spring:
  codec:
    max-in-memory-size: 1024
  webflux:
    multipart:
      max-in-memory-size: 1KB
      max-parts: 3
      max-disk-usage-per-part: 1KB
      max-headers-size: 5KB
  devtools:
    restart:
      pollInterval: 2s
      enabled: true
      # excludes: 
      # additional-exclude:
      # trigger-file:
    livereload:
      enabled: true
      port: ${TOBF_LIVERELOAD_PORT:35792}
server:
  port: ${TOBF_SERVER_PORT:4044}
logging:
  level:
    root: INFO
    me:
      resp:
        fileuploaddemo: DEBUG