spring:
  devtools:
    restart:
      pollInterval: 2s
      enabled: true
      # excludes: 
      # additional-exclude:
      # trigger-file:
    livereload:
      enabled: true
      port: ${TOBE_LIVERELOAD_PORT:35792}
server:
  port: 4044